#!/usr/bin/env bash

set -e

function cleanup {
  docker rm "$(docker kill ${CONTAINER_ID})"
  rm "${SERVICE_NAME}.cid"
}

ES_PORT=9200

SERVICE_NAME=`basename $(pwd) | sed 's/^platform-//'`
CONTAINER_NAME="$1"

docker run -itd \
  --cidfile="${SERVICE_NAME}.cid" \
  "${CONTAINER_NAME}"

CONTAINER_ID=`cat "${SERVICE_NAME}.cid"`

trap cleanup EXIT
sleep 10

docker exec "${CONTAINER_ID}" \
  wget -qO - "http://localhost:${ES_PORT}/_cat/health?v"

CODE=$?

exit $CODE
